### ISSUE TITLE
Sorry for this off topic issue.

### ISSUE THREAD

**Issue by Dhyfer1** [Icecovery/IMEIndicator#23]
Hi @Icecovery 

Sorry for this issue that is not related to your project, just that I like the pointer that appears in the gif images and I wanted to know if you can share it. Also, can you tell me that app you used to show the red circles every time you click?

It's just those two things. I await your answer 🙂

**Comment by Icecovery** [comment]
Hi @Dhyfer1 , the cursor is from [Material Design Cursors Dark](https://www.deviantart.com/jepricreations/art/Material-Design-Cursors-Dark-756850032) by [jepriCreations](https://www.deviantart.com/jepricreations).

The red circle is a feature in [HoneyCam](https://bandisoft.com/honeycam/), the software I used to record the GIF. There is a similar feature in [PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/) if you want to have it outside recordings.

**Comment by Dhyfer1** [comment]
Wow. Thank you very much for the cursors and for honeycam, 🙂 I didn't know about this program, it seems very interesting.

I use Powertoys but the click effect is not the same. When the "Mouse highlighter" feature in Powertoys is on, it only shows a colored circle, and not a ring as can be seen in your gif.

I haven't had the problem you show in the gif on Windows 11, but I have starred your repo if I need to in the future.

Thank you, and have a nice day. 👍

**Comment by Dhyfer1** [comment]
> The red circle is a feature in [HoneyCam](https://bandisoft.com/honeycam/), the software I used to record the GIF. 

Hi. i downloaded honeycam, but change the color of the click effect it's only for paid users 😢. You bought honeycam or did you activate it with a crack?

**Comment by Icecovery** [comment]
Hi @Dhyfer1 , I did purchase a permanent license for HoneyCam so I was unaware that the particular feature was only available for paid users. 
I suggest you raise this as a feature request over at the PowerToys repository.

**Comment by Dhyfer1** [comment]
> I suggest you raise this as a feature request over at the PowerToys repository.

I hadn't thought of that, okay, I'll do it.  And whether or not Microsoft wants to implement that feature, I've found [clickshow](https://github.com/cuiliang/ClickShow) and it's very customizable.  I recommend it to you. 👍
