### ISSUE TITLE
Lock the IME

### ISSUE THREAD

**Issue by bilogic** [Icecovery/IMEIndicator#34]
My IME changes by itself whenever I focus on a non-unicode app. Full description here https://superuser.com/questions/1827327/stop-w10-ime-from-changing-when-focused-on-non-unicode-program

I would like it to stay fixed, is this something you can add on? Thanks!

**Comment by Icecovery** [comment]
Hi, As this project is an IME indicator, the feature you are requesting is outside this project's scope. 

I believe what you want is to turn off the "Let me use a different input method for each app windows" option built-in Windows 10. You can find it on the "Advanced keyboard settings" page.

**Comment by bilogic** [comment]
@Icecovery thanks, but I already have `Let me use a different input method for each app windows` disabled. 

I spent the time to narrow down the cause, my description on superuser points to the exact cause that makes the IME change language.
